#! /usr/bin/env python3

"""
This is a tester script to visualise the output of
the Data class in Helpers.py.
The line is the x and y generated by linear_regress().
The dots are x plotted against y passed through add_variance()

Note that the line will not necessarily be the best fit;
it is not generated from the points (by OLS or similar),
but is the generated by Data, and the dot plots are
then randomly offset.
"""

from Helpers import Data
from matplotlib import pyplot as plt

# Get dataset from Helpers.py
d = Data(15)
x, y = d.linear_regres()
yvar = d.add_variance(y)

# Plot points
plt.scatter(x, yvar)
plt.plot(x, y, 'r')

# Make labels
plt.title('Test Plot with Variance')
plt.xlabel('x values')
plt.ylabel('y values')

plt.show()
